import { useMutation, useQuery } from '@tanstack/react-query';
import { ChevronRight, Send } from 'lucide-react';
import { useState } from 'react';
import type { AiDiagnosis, Equipment } from '@fengsui/shared';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, ErrorState, Loading, RiskBadge } from '../components/ui';
import { api, postJson } from '../services/api';

const presets = ['当前风险最高的设备是什么？', '为什么1号引风机健康度下降？', '这条预警最可能是什么原因？', '建议优先检查哪些部位？', '是否建议立即停机？', '当前备件库存是否满足维修需求？', '最近有哪些重复发生的设备异常？', '哪些工单即将超期？'];
interface ChatMessage { id: string; role: 'user' | 'assistant'; text?: string; diagnosis?: AiDiagnosis }

function DiagnosisAnswer({ item }: { item: AiDiagnosis }) {
  return <div className="mt-3 space-y-3"><div className="rounded border border-orange-200 bg-orange-50 p-3 text-sm font-medium text-orange-900">{item.riskJudgment}</div><div className="grid gap-3 text-sm sm:grid-cols-2"><div><span className="text-xs font-semibold text-[#8F959E]">1. 当前工况</span><p className="mt-1">{item.operatingCondition}</p></div><div><span className="text-xs font-semibold text-[#8F959E]">2. 异常指标</span><p className="mt-1">{item.abnormalIndicators.join('、')}</p></div><div className="sm:col-span-2"><span className="text-xs font-semibold text-[#8F959E]">3. 趋势证据</span><ul className="mt-1 space-y-1">{item.trendEvidence.map((value) => <li key={value}>· {value}</li>)}</ul></div><div><span className="text-xs font-semibold text-[#8F959E]">4. 疑似原因</span><ul className="mt-1 space-y-1">{item.suspectedCauses.map((value) => <li key={value}>· {value}</li>)}</ul></div><div><span className="text-xs font-semibold text-[#8F959E]">5. 推荐检查项目</span><ul className="mt-1 space-y-1">{item.inspectionItems.map((value) => <li key={value}>· {value}</li>)}</ul></div><div><span className="text-xs font-semibold text-[#8F959E]">6. 建议处理时限</span><p className="mt-1 font-medium text-orange-700">{item.suggestedDeadline}</p></div><div><span className="text-xs font-semibold text-[#8F959E]">7. 关联备件</span><p className="mt-1">{item.relatedSpareParts.join('、') || '暂未匹配到明确备件'}</p></div></div><div className="rounded border border-[#E5E6EB] bg-[#FAFAFA] p-3 text-xs"><div className="flex items-center justify-between"><span>规则匹配度</span><strong className="text-[#3A3F47]">{Math.round(item.confidence * 100)}%</strong></div><p className="mt-1 text-[#8F959E]">基于模拟数据和规则库计算，仅供辅助参考。</p></div><p className="rounded border border-[#E5E6EB] p-3 text-xs leading-5 text-[#646A73]">{item.riskNotice}</p></div>;
}

export function AiAssistantPage() {
  const equipmentQuery = useQuery({ queryKey: ['equipment'], queryFn: () => api<Equipment[]>('/equipment') });
  const [deviceId, setDeviceId] = useState('IDF-001'); const [input, setInput] = useState('');
  const [messages, setMessages] = useState<ChatMessage[]>([{ id: 'welcome', role: 'assistant', text: '这里是烽燧辅助研判。当前使用比赛演示规则库，并会引用设备工况、监测趋势和知识条目辅助判断。请选择设备或直接点击预置问题。' }]);
  const mutation = useMutation({ mutationFn: ({ question, id }: { question: string; id: string }) => postJson<AiDiagnosis>('/ai/diagnose', { deviceId: id, question }), onSuccess: (result) => setMessages((items) => [...items, { id: crypto.randomUUID(), role: 'assistant', diagnosis: result }]) });
  const send = (question: string) => { const text = question.trim(); if (!text || mutation.isPending) return; setMessages((items) => [...items, { id: crypto.randomUUID(), role: 'user', text }]); mutation.mutate({ question: text, id: deviceId }); setInput(''); };
  if (equipmentQuery.isLoading) return <Loading />; if (equipmentQuery.isError) return <ErrorState error={equipmentQuery.error} />;
  const current = equipmentQuery.data?.find((item) => item.deviceId === deviceId);
  return <div><PageHeader title="辅助研判" description="基于工况、趋势证据与运维知识库的规则辅助判断" /><DemoDisclaimer />
    <div className="mt-4 grid min-h-[680px] gap-4 xl:grid-cols-[300px_1fr]"><aside className="panel p-4"><div className="mb-3 text-sm font-semibold text-[#1F2329]">常用问题</div><div className="space-y-1">{presets.map((item) => <button key={item} className="flex w-full items-center justify-between rounded px-3 py-2.5 text-left text-xs leading-5 text-[#646A73] hover:bg-[#F2F3F5] hover:text-[#1F2329]" onClick={() => send(item)}><span>{item}</span><ChevronRight size={13} className="shrink-0" /></button>)}</div><div className="mt-5 border-t border-[#E5E6EB] pt-4"><label className="label">研判设备</label><select className="input" value={deviceId} onChange={(event) => setDeviceId(event.target.value)}>{equipmentQuery.data?.map((item) => <option key={item.deviceId} value={item.deviceId}>{item.deviceName}</option>)}</select>{current && <div className="mt-3 rounded border border-[#E5E6EB] bg-[#FAFAFA] p-3"><div className="flex items-center justify-between"><span className="text-sm font-medium">{current.deviceName}</span><RiskBadge level={current.riskLevel} /></div><div className="mt-2 flex items-end gap-2"><span className="text-2xl font-semibold">{current.healthScore}</span><span className="mb-1 text-[11px] text-[#8F959E]">当前健康度</span></div><div className="mt-2 text-xs text-[#646A73]">{current.operatingCondition}</div></div>}</div></aside>
      <section className="panel flex min-h-0 flex-col overflow-hidden"><div className="flex items-center justify-between border-b border-[#E5E6EB] px-5 py-3.5"><div><div className="text-sm font-semibold text-[#1F2329]">设备辅助研判</div><div className="text-[11px] text-[#8F959E]">规则库 · 运维知识库</div></div><div className="flex items-center gap-1.5 text-[11px] text-[#646A73]"><span className="h-1.5 w-1.5 rounded-full bg-[#7FA58A]" />可用</div></div><div className="scrollbar-thin flex-1 space-y-5 overflow-y-auto bg-[#FAFAFA] p-5">{messages.map((message) => <div key={message.id} className={`flex gap-3 ${message.role === 'user' ? 'flex-row-reverse' : ''}`}><div className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-xs font-medium ${message.role === 'user' ? 'bg-[#4E5969] text-white' : 'border border-[#D9DADC] bg-white text-[#646A73]'}`}>{message.role === 'user' ? '用' : '研'}</div><div className={`max-w-[820px] rounded px-4 py-3 text-sm leading-6 ${message.role === 'user' ? 'bg-[#4E5969] text-white' : 'border border-[#D9DADC] bg-white text-[#3A3F47]'}`}>{message.text}{message.diagnosis && <DiagnosisAnswer item={message.diagnosis} />}</div></div>)}{mutation.isPending && <div className="flex gap-3"><div className="flex h-8 w-8 items-center justify-center rounded-full border border-[#D9DADC] bg-white text-xs text-[#646A73]">研</div><div className="rounded border border-[#D9DADC] bg-white px-4 py-3 text-sm text-[#646A73]">正在比对工况基准、趋势和知识库…</div></div>}{mutation.isError && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">研判请求失败：{mutation.error.message}</div>}</div><form className="border-t border-[#E5E6EB] bg-white p-4" onSubmit={(event) => { event.preventDefault(); send(input); }}><div className="flex gap-2"><input className="input min-h-11" value={input} onChange={(event) => setInput(event.target.value)} placeholder="输入关于设备风险、原因、检查项或备件的问题…" /><button className="btn-primary min-w-24" disabled={!input.trim() || mutation.isPending}><Send size={16} />发送</button></div><p className="mt-2 text-center text-[11px] text-[#8F959E]">辅助研判不替代现场检查和安全决策，请结合设备说明书与企业规程使用</p></form></section></div>
  </div>;
}
