import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BellRing, Check, ClipboardPlus, Download, Eye, Search, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Alert, Equipment, IndicatorKey, OperationLog, TelemetryPoint, WorkOrder } from '@fengsui/shared';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, Empty, ErrorState, Loading, Modal, Panel, RiskBadge, StatusBadge, Toast } from '../components/ui';
import { api, idempotencyKey, postJson } from '../services/api';

interface AlertDetail extends Alert { telemetry: TelemetryPoint[]; logs: OperationLog[] }
const names: Record<IndicatorKey, string> = { vibration: '振动', temperature: '温度', current: '电流', pressure: '压力', speed: '转速' };

export function AlertsPage() {
  const navigate = useNavigate(); const { alertId } = useParams(); const queryClient = useQueryClient();
  const [risk, setRisk] = useState(''); const [status, setStatus] = useState(''); const [device, setDevice] = useState(''); const [search, setSearch] = useState(''); const [from, setFrom] = useState(''); const [toast, setToast] = useState('');
  const query = useQuery({ queryKey: ['alerts'], queryFn: () => api<Alert[]>('/alerts') });
  const detailQuery = useQuery({ queryKey: ['alert', alertId], queryFn: () => api<AlertDetail>(`/alerts/${alertId}`), enabled: Boolean(alertId) });
  const currentDeviceQuery = useQuery({ queryKey: ['equipment', detailQuery.data?.deviceId], queryFn: () => api<Equipment>(`/equipment/${detailQuery.data!.deviceId}`), enabled: Boolean(detailQuery.data?.deviceId) });
  const relatedOrderQuery = useQuery({ queryKey: ['work-order', detailQuery.data?.relatedWorkOrderId], queryFn: () => api<WorkOrder>(`/work-orders/${detailQuery.data!.relatedWorkOrderId}`), enabled: Boolean(detailQuery.data?.relatedWorkOrderId) });
  const update = useMutation({ mutationFn: ({ path, body }: { path: string; body: unknown }) => postJson<Alert>(path, body), onSuccess: async () => { setToast('预警状态已更新'); await queryClient.invalidateQueries({ queryKey: ['alerts'] }); await queryClient.invalidateQueries({ queryKey: ['alert', alertId] }); } });
  const createOrder = useMutation({ mutationFn: (id: string) => postJson<WorkOrder>(`/alerts/${id}/create-work-order`, { assignee: '张工', assigneeUserId: 'zhang-gong', idempotencyKey: idempotencyKey('alert-order') }), onSuccess: (order) => navigate(`/work-orders/${order.workOrderId}`) });
  const notify = useMutation({ mutationFn: (id: string) => postJson<{ delivered: boolean; error?: string }>('/notifications/alert', { alertId: id }), onSuccess: (result) => setToast(result.delivered ? '预警消息已发送/预览成功' : `消息未送达：${result.error}`) });
  const rows = useMemo(() => (query.data ?? []).filter((item) => (!risk || item.riskLevel === risk) && (!status || item.alertStatus === status) && (!device || item.deviceId === device) && (!from || item.alertTime >= new Date(from).toISOString()) && (!search || `${item.deviceName}${item.alertId}${item.abnormalIndicators.join('')}`.toLowerCase().includes(search.toLowerCase()))), [query.data, risk, status, device, from, search]);
  if (query.isLoading) return <Loading />; if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const devices = [...new Map((query.data ?? []).map((item) => [item.deviceId, item.deviceName])).entries()];
  const exportCsv = () => { const content = [['预警编号', '设备', '风险等级', '健康度', '异常指标', '状态', '触发时间'], ...rows.map((item) => [item.alertId, item.deviceName, item.riskLevel, item.healthScore, item.abnormalIndicators.join('|'), item.alertStatus, item.alertTime])].map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(',')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([`\uFEFF${content}`], { type: 'text/csv;charset=utf-8' })); link.download = `烽燧预警-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); };
  const detail = detailQuery.data;
  const currentHealth = currentDeviceQuery.data?.healthScore ?? detail?.telemetry.at(-1)?.healthScore ?? detail?.healthScore;
  const closeReason = detail?.alertStatus === '误报'
    ? '经人工复核后标记为误报'
    : detail?.alertStatus === '已关闭'
      ? relatedOrderQuery.data?.status === '已完成' && relatedOrderQuery.data.verificationResult ? '维修完成并验证通过' : detail.relatedWorkOrderId ? '关联工单完成后关闭' : '指标恢复或人工确认后关闭'
      : '—';
  return <div><PageHeader title="预警中心" description="集中确认、分析和处置设备异常预警" actions={<button className="btn-secondary" onClick={exportCsv}><Download size={16} />导出当前结果</button>} /><DemoDisclaimer compact />
    <div className="panel mt-4 p-4"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-6"><div className="relative xl:col-span-2"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className="input pl-9" placeholder="搜索预警、设备或异常指标" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select className="input" value={risk} onChange={(event) => setRisk(event.target.value)}><option value="">全部风险等级</option><option>关注</option><option>二级预警</option><option>高风险</option></select><select className="input" value={device} onChange={(event) => setDevice(event.target.value)}><option value="">全部设备</option>{devices.map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select><select className="input" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option>{['待确认', '已确认', '已生成工单', '处理中', '已关闭', '误报'].map((item) => <option key={item}>{item}</option>)}</select><input className="input" type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></div><div className="mt-3 text-xs text-slate-400">当前筛选 {rows.length} 条预警</div></div>
    <div className="panel mt-4 table-wrap">{rows.length ? <table className="data-table"><thead><tr><th>预警编号 / 时间</th><th>设备</th><th>触发风险 / 健康度</th><th>触发时工况</th><th>异常指标</th><th>当前状态</th><th>规则匹配度</th><th>操作</th></tr></thead><tbody>{rows.map((item) => <tr key={item.alertId}><td><div className="font-mono text-xs">{item.alertId}</div><div className="subtle mt-1">{new Date(item.alertTime).toLocaleString('zh-CN')}</div></td><td><button className="font-semibold text-[#3A3F47] hover:underline" onClick={() => navigate(`/equipment/${item.deviceId}`)}>{item.deviceName}</button></td><td><div className="flex items-center gap-2"><RiskBadge level={item.riskLevel} /><strong>{item.healthScore}</strong></div></td><td>{item.operatingCondition}</td><td>{item.abnormalIndicators.map((value) => <span key={value} className="mr-1 inline-flex rounded bg-orange-50 px-2 py-1 text-xs text-orange-700">{value}</span>)}</td><td><StatusBadge status={item.alertStatus} /></td><td>{Math.round(item.confidence * 100)}%</td><td><button className="btn-secondary min-h-8 px-2.5 py-1.5" onClick={() => navigate(`/alerts/${item.alertId}`)}><Eye size={14} />详情</button></td></tr>)}</tbody></table> : <Empty />}</div>
    {alertId && <Modal title="预警详情" onClose={() => navigate('/alerts')} width="max-w-5xl">{detailQuery.isLoading ? <Loading /> : detail ? <div><div className="border-b border-[#E5E6EB] pb-4"><h3 className="text-lg font-semibold text-[#1F2329]">{detail.deviceName}</h3><div className="mt-1 font-mono text-xs text-[#8F959E]">{detail.alertId}</div></div><div className="grid border-b border-l border-[#E5E6EB] sm:grid-cols-2 lg:grid-cols-4"><div className="border-r border-t border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">触发风险</div><div className="mt-2"><RiskBadge level={detail.riskLevel} /></div></div><div className="border-r border-t border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">预警状态</div><div className="mt-2"><StatusBadge status={detail.alertStatus} /></div></div><div className="border-r border-t border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">触发时间</div><div className="mt-2 text-sm text-[#1F2329]">{new Date(detail.alertTime).toLocaleString('zh-CN')}</div></div><div className="border-r border-t border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">关闭时间</div><div className="mt-2 text-sm text-[#1F2329]">{detail.closedAt ? new Date(detail.closedAt).toLocaleString('zh-CN') : '—'}</div></div><div className="border-r border-t border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">触发时健康度</div><div className="mt-1 text-xl font-semibold text-orange-700">{detail.healthScore}</div></div><div className="border-r border-t border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">当前健康度</div><div className="mt-1 text-xl font-semibold text-[#1F2329]">{currentHealth ?? '—'}</div></div><div className="border-r border-t border-[#E5E6EB] p-3 sm:col-span-2"><div className="text-xs text-[#8F959E]">关闭原因</div><div className="mt-2 text-sm text-[#1F2329]">{closeReason}</div></div></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-3"><Panel title="触发证据"><div className="space-y-3 p-4 text-sm text-[#3A3F47]"><div><span className="text-[#8F959E]">触发时工况：</span>{detail.operatingCondition}</div><div><span className="text-[#8F959E]">异常指标：</span>{detail.abnormalIndicators.join('、')}</div><div><span className="text-[#8F959E]">规则触发：</span>{detail.abnormalIndicators.join('与')}连续偏离该工况允许范围</div><div><span className="text-[#8F959E]">趋势证据：</span>最近6小时异常指标持续上升，触发时健康度降至 {detail.healthScore}</div></div></Panel><Panel title="辅助研判"><div className="p-4 text-sm leading-6 text-[#3A3F47]"><p>{detail.aiAnalysis}</p><p className="mt-3"><strong className="text-[#1F2329]">疑似原因：</strong>{detail.suspectedCause}</p><p className="mt-3"><strong className="text-[#1F2329]">建议时限：</strong>{detail.suggestedDeadline}</p></div></Panel><Panel title="风险说明"><div className="p-4 text-sm leading-6 text-[#3A3F47]">存在异常趋势继续发展的风险，但规则结果不能替代现场检查。是否停机应由现场负责人结合安全规程决定。<div className="mt-3 rounded border border-[#E5E6EB] bg-[#FAFAFA] p-3 text-[#3A3F47]"><div className="font-medium">规则匹配度 {Math.round(detail.confidence * 100)}%</div><div className="mt-1 text-xs text-[#8F959E]">基于模拟数据和规则库计算，仅供辅助参考。</div></div></div></Panel></div>
      <div className="mt-4 grid gap-4 lg:grid-cols-[1.2fr_1fr]"><Panel title="指标贡献度"><div className="h-60 p-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={Object.entries(detail.indicatorContributions).map(([key, value]) => ({ name: names[key as IndicatorKey], contribution: value }))}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#EDEEF0" /><XAxis dataKey="name" tick={{ fill: '#646A73', fontSize: 11 }} /><YAxis unit="%" tick={{ fill: '#8F959E', fontSize: 11 }} /><Tooltip formatter={(value) => [`${value}%`, '贡献度']} /><Bar isAnimationActive={false} dataKey="contribution" name="贡献度" fill="#C8894A" radius={[2, 2, 0, 0]} /></BarChart></ResponsiveContainer></div></Panel><Panel title="检修建议与处理记录"><div className="p-4"><ul className="space-y-2 text-sm text-[#3A3F47]">{detail.maintenanceSuggestion.map((item) => <li key={item}>· {item}</li>)}</ul><div className="mt-4 border-t border-[#E5E6EB] pt-4 text-xs text-[#646A73]">{detail.acknowledgedBy ? `由 ${detail.acknowledgedBy} 于 ${new Date(detail.acknowledgedAt!).toLocaleString('zh-CN')} 确认` : detail.closedAt ? '未单独确认；由维修闭环关闭' : '尚未确认'}{detail.closedAt && <div className="mt-2">关闭于 {new Date(detail.closedAt).toLocaleString('zh-CN')} · {closeReason}</div>}</div></div></Panel></div>
      <div className="mt-5 flex flex-wrap justify-end gap-2"><button className="btn-secondary" onClick={() => notify.mutate(detail.alertId)}><BellRing size={15} />发送预警消息</button><button className="btn-secondary" disabled={detail.alertStatus !== '待确认'} onClick={() => update.mutate({ path: `/alerts/${detail.alertId}/acknowledge`, body: { operator: '黄浩' } })}><Check size={15} />确认预警</button><button className="btn-danger" disabled={!['待确认', '已确认'].includes(detail.alertStatus)} onClick={() => window.confirm('确认标记为误报？该操作会关闭预警。') && update.mutate({ path: `/alerts/${detail.alertId}/false-positive`, body: { operator: '黄浩' } })}><XCircle size={15} />标记误报</button>{detail.relatedWorkOrderId ? <button className="btn-primary" onClick={() => navigate(`/work-orders/${detail.relatedWorkOrderId}`)}>查看关联工单</button> : ['待确认', '已确认'].includes(detail.alertStatus) ? <button className="btn-primary" onClick={() => createOrder.mutate(detail.alertId)}><ClipboardPlus size={15} />生成工单</button> : null}</div>
      <p className="mt-5 rounded border border-[#E5E6EB] bg-[#FAFAFA] p-3 text-xs leading-5 text-[#646A73]">本结果根据模拟数据和规则模型生成，仅用于比赛方案展示。实际生产应用需结合企业真实数据、设备说明书、安全规程和专业人员判断。</p></div> : <ErrorState error={detailQuery.error} />}</Modal>}
    {toast && <Toast message={toast} onClose={() => setToast('')} />}{(update.isError || createOrder.isError || notify.isError) && <Toast type="error" message={(update.error ?? createOrder.error ?? notify.error)?.message ?? '操作失败'} onClose={() => { update.reset(); createOrder.reset(); notify.reset(); }} />}
  </div>;
}
