import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Box, ClipboardList, Eye, Grid2X2, List, Pencil, Plus, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Line, LineChart, ResponsiveContainer } from 'recharts';
import type { Equipment, TelemetryPoint } from '@fengsui/shared';
import { equipmentInputSchema } from '@fengsui/shared';
import type { z } from 'zod';
import { DataTable, DetailDrawer, FilterBar, IndustrialPanel, StatusNode } from '../components/industrial';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, Empty, ErrorState, Loading, Modal, RiskBadge, StatusBadge, Toast } from '../components/ui';
import { api, patchJson, postJson } from '../services/api';
import { riskColor } from '../theme/industrialTheme';
import './equipment.css';

type FormData = z.infer<typeof equipmentInputSchema>;
const emptyForm: FormData = { deviceName: '', deviceType: '离心式引风机', systemArea: '烟气系统', manufacturer: '', model: '', installationDate: new Date().toISOString().slice(0, 10), runningStatus: '运行', operatingCondition: '稳定运行', responsiblePerson: '张工', responsibleUserId: 'demo-user', location: '' };

function EquipmentForm({ device, onClose }: { device?: Equipment; onClose: () => void }) {
  const queryClient = useQueryClient(); const [confirming, setConfirming] = useState(false);
  const { register, handleSubmit, formState: { errors }, getValues } = useForm<FormData>({ resolver: zodResolver(equipmentInputSchema), defaultValues: device ? { deviceName: device.deviceName, deviceType: device.deviceType, systemArea: device.systemArea, manufacturer: device.manufacturer, model: device.model, installationDate: device.installationDate, runningStatus: device.runningStatus, operatingCondition: device.operatingCondition, responsiblePerson: device.responsiblePerson, responsibleUserId: device.responsibleUserId, location: device.location } : emptyForm });
  const mutation = useMutation({ mutationFn: (body: FormData) => device ? patchJson<Equipment>(`/equipment/${device.deviceId}`, body) : postJson<Equipment>('/equipment', body), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['equipment'] }); onClose(); } });
  const fields: Array<{ name: keyof FormData; label: string; type?: string }> = [{ name: 'deviceName', label: '设备名称' }, { name: 'deviceType', label: '设备类型' }, { name: 'systemArea', label: '系统区域' }, { name: 'manufacturer', label: '制造商' }, { name: 'model', label: '型号' }, { name: 'installationDate', label: '安装日期', type: 'date' }, { name: 'responsiblePerson', label: '负责人' }, { name: 'location', label: '安装位置' }];
  return <Modal title={device ? `编辑设备 · ${device.deviceName}` : '新增设备'} onClose={onClose}><form onSubmit={handleSubmit(() => setConfirming(true))}><div className="grid gap-4 sm:grid-cols-2">{fields.map((field) => <label key={field.name}><span className="label">{field.label}</span><input className="input" type={field.type} {...register(field.name)} />{errors[field.name] && <span className="mt-1 block text-xs text-[var(--industrial-danger)]">{String(errors[field.name]?.message)}</span>}</label>)}<label><span className="label">运行状态</span><select className="input" {...register('runningStatus')}><option>运行</option><option>停机</option><option>检修</option><option>离线</option></select></label><label><span className="label">当前工况</span><select className="input" {...register('operatingCondition')}><option>停机</option><option>启动</option><option>低负荷</option><option>稳定运行</option><option>高负荷稳定运行</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>取消</button><button className="btn-primary" disabled={mutation.isPending}>{device ? '保存修改' : '新增设备'}</button></div></form>{confirming && <div className="absolute inset-0 flex items-center justify-center rounded bg-[#071827]/95 p-6"><div className="max-w-sm text-center"><h3 className="font-semibold text-[var(--industrial-text)]">确认提交设备信息？</h3><p className="mt-2 text-sm text-[var(--industrial-text-secondary)]">写操作将记录在设备台账中。当前为模拟演示数据。</p><div className="mt-5 flex justify-center gap-2"><button className="btn-secondary" onClick={() => setConfirming(false)}>返回检查</button><button className="btn-primary" onClick={() => mutation.mutate(getValues())}>确认提交</button></div></div></div>}</Modal>;
}

function EquipmentDrawer({ device, onClose }: { device: Equipment; onClose: () => void }) {
  const navigate = useNavigate();
  const telemetry = useQuery({ queryKey: ['telemetry', device.deviceId, '24h', 'drawer'], queryFn: () => api<TelemetryPoint[]>(`/equipment/${device.deviceId}/telemetry?range=24h`) });
  const data = telemetry.data?.slice(-24) ?? [];
  return <DetailDrawer title={device.deviceName} subtitle={`${device.deviceId} · ${device.deviceType}`} onClose={onClose} footer={<><button className="btn-secondary" onClick={() => navigate(`/work-orders?search=${device.deviceId}`)}><ClipboardList size={15} />查看工单</button>{device.deviceId === 'IDF-001' && <button className="btn-secondary" onClick={() => navigate('/digital-twin?equipment=IDF-01')}><Box size={15} />查看3D</button>}<button className="btn-primary" onClick={() => navigate(`/equipment/${device.deviceId}`)}>完整设备详情</button></>}>
    <div className="equipment-drawer__status"><div><StatusNode status={device.riskLevel} size="lg" pulse={device.riskLevel === '高风险'} /><span><strong>{device.runningStatus}</strong><small>{device.operatingCondition}</small></span></div><div className="industrial-data"><strong>{device.healthScore}</strong><small>当前健康度</small></div></div>
    <div className="equipment-health-track"><span style={{ width: `${device.healthScore}%`, background: riskColor(device.riskLevel) }} /></div>
    <IndustrialPanel title="最近24小时健康度微型趋势" meta="来自设备遥测接口" className="mt-4"><div className="h-28 p-3">{telemetry.isLoading ? <Loading label="正在加载遥测…" /> : data.length ? <ResponsiveContainer width="100%" height="100%"><LineChart data={data}><Line type="monotone" dataKey="healthScore" stroke={riskColor(device.riskLevel)} strokeWidth={2} dot={false} isAnimationActive={false} /></LineChart></ResponsiveContainer> : <Empty title="暂无遥测趋势" />}</div></IndustrialPanel>
    <div className="equipment-drawer__metrics"><div><span>振动速度</span><strong className="industrial-data">{device.vibration} <small>mm/s</small></strong></div><div><span>轴承温度</span><strong className="industrial-data">{device.temperature} <small>℃</small></strong></div><div><span>电机电流</span><strong className="industrial-data">{device.current} <small>A</small></strong></div><div><span>运行转速</span><strong className="industrial-data">{device.speed} <small>r/min</small></strong></div></div>
    <div className="equipment-drawer__facts">{[['系统区域', device.systemArea], ['安装位置', device.location], ['制造商', device.manufacturer], ['设备型号', device.model], ['负责人', device.responsiblePerson], ['累计运行', `${device.runningHours.toLocaleString()} h`], ['下次保养', device.nextMaintenanceDate], ['数据更新', new Date(device.updatedAt).toLocaleString('zh-CN')]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>
  </DetailDrawer>;
}

export function EquipmentPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const [view, setView] = useState<'table' | 'card'>('table');
  const [editing, setEditing] = useState<Equipment | 'new' | null>(null); const [selected, setSelected] = useState<Equipment | null>(null); const [toast, setToast] = useState('');
  const query = useQuery({ queryKey: ['equipment'], queryFn: () => api<Equipment[]>('/equipment') });
  const rows = useMemo(() => {
    const all = query.data ?? []; const search = (params.get('search') ?? '').toLowerCase();
    return all.filter((item) => (!search || `${item.deviceName}${item.deviceId}${item.deviceType}`.toLowerCase().includes(search)) && (!params.get('deviceType') || item.deviceType === params.get('deviceType')) && (!params.get('systemArea') || item.systemArea === params.get('systemArea')) && (!params.get('riskLevel') || item.riskLevel === params.get('riskLevel')) && (!params.get('runningStatus') || item.runningStatus === params.get('runningStatus'))).sort((a, b) => params.get('sort') === 'healthDesc' ? b.healthScore - a.healthScore : a.healthScore - b.healthScore);
  }, [query.data, params]);
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next); };
  if (query.isLoading) return <Loading />; if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const types = [...new Set((query.data ?? []).map((item) => item.deviceType))]; const areas = [...new Set((query.data ?? []).map((item) => item.systemArea))];
  return <div className="app-page equipment-page"><PageHeader title="设备台账" description="统一管理关键设备档案、运行状态、工况与责任人" actions={<button className="btn-primary" onClick={() => setEditing('new')}><Plus size={16} />新增设备</button>} /><DemoDisclaimer compact />
    <FilterBar summary={<>当前显示 <strong className="industrial-data text-[var(--industrial-primary)]">{rows.length}</strong> 台设备 · 点击行打开设备详情抽屉</>}><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-[var(--industrial-text-muted)]" size={17} /><input className="input pl-9" placeholder="搜索设备名称、编号或类型" value={params.get('search') ?? ''} onChange={(event) => setFilter('search', event.target.value)} /></div>{[['deviceType', '全部类型', types], ['systemArea', '全部区域', areas], ['riskLevel', '全部风险', ['健康', '关注', '二级预警', '高风险']], ['runningStatus', '全部状态', ['运行', '停机', '检修', '离线']]].map(([key, label, options]) => <select key={String(key)} className="input xl:w-40" value={params.get(String(key)) ?? ''} onChange={(event) => setFilter(String(key), event.target.value)}><option value="">{String(label)}</option>{(options as string[]).map((value) => <option key={value}>{value}</option>)}</select>)}<select className="input xl:w-40" value={params.get('sort') ?? 'healthAsc'} onChange={(event) => setFilter('sort', event.target.value)}><option value="healthAsc">健康度：低到高</option><option value="healthDesc">健康度：高到低</option></select><div className="equipment-view-toggle"><button className={view === 'table' ? 'is-active' : ''} onClick={() => setView('table')} aria-label="表格视图"><List size={17} /></button><button className={view === 'card' ? 'is-active' : ''} onClick={() => setView('card')} aria-label="卡片视图"><Grid2X2 size={17} /></button></div></FilterBar>

    {view === 'table' ? <DataTable className="mt-4">{rows.length ? <><thead><tr><th>设备</th><th>类型 / 区域</th><th>状态 / 工况</th><th>健康度</th><th>实时指标</th><th>负责人</th><th>更新时间</th><th>快捷操作</th></tr></thead><tbody>{rows.map((item) => <tr key={item.deviceId} className="cursor-pointer" onClick={() => setSelected(item)}><td><div className="equipment-name"><StatusNode status={item.riskLevel} pulse={item.riskLevel === '高风险'} /><span><strong>{item.deviceName}</strong><small className="industrial-data">{item.deviceId}</small></span></div></td><td><div>{item.deviceType}</div><div className="subtle mt-1">{item.systemArea}</div></td><td><StatusBadge status={item.runningStatus} /><div className="subtle mt-1">{item.operatingCondition}</div></td><td><div className="equipment-health-cell"><span className="industrial-data">{item.healthScore}</span><div><i><b style={{ width: `${item.healthScore}%`, background: riskColor(item.riskLevel) }} /></i><RiskBadge level={item.riskLevel} /></div></div></td><td><div className="industrial-data text-xs">振动 {item.vibration} mm/s</div><div className="industrial-data mt-1 text-xs">温度 {item.temperature}℃</div></td><td>{item.responsiblePerson}</td><td className="industrial-data text-[10px]">{new Date(item.updatedAt).toLocaleString('zh-CN')}</td><td><div className="equipment-row-actions"><button title="查看详情" onClick={(event) => { event.stopPropagation(); setSelected(item); }}><Eye size={15} /></button>{item.deviceId === 'IDF-001' && <button title="查看3D" onClick={(event) => { event.stopPropagation(); navigate('/digital-twin?equipment=IDF-01'); }}><Box size={15} /></button>}<button title="编辑" onClick={(event) => { event.stopPropagation(); setEditing(item); }}><Pencil size={15} /></button></div></td></tr>)}</tbody></> : <tbody><tr><td><Empty /></td></tr></tbody>}</DataTable> : <div className="equipment-card-grid">{rows.map((item) => <button key={item.deviceId} className="equipment-card" onClick={() => setSelected(item)}><div className="equipment-card__header"><span><StatusNode status={item.riskLevel} pulse={item.riskLevel === '高风险'} /><strong>{item.deviceName}</strong></span><RiskBadge level={item.riskLevel} /></div><div className="industrial-data equipment-card__id">{item.deviceId} · {item.deviceType}</div><div className="equipment-card__health"><strong className="industrial-data">{item.healthScore}</strong><span><small>当前健康度 / 100</small><i><b style={{ width: `${item.healthScore}%`, background: riskColor(item.riskLevel) }} /></i></span></div><div className="equipment-card__metrics"><span>振动<strong className="industrial-data">{item.vibration} mm/s</strong></span><span>温度<strong className="industrial-data">{item.temperature} ℃</strong></span><span>工况<strong>{item.operatingCondition}</strong></span><span>负责人<strong>{item.responsiblePerson}</strong></span></div>{item.deviceId === 'IDF-001' && <div className="equipment-card__twin"><Box size={13} />支持3D数字孪生</div>}</button>)}</div>}
    {selected && <EquipmentDrawer device={selected} onClose={() => setSelected(null)} />}
    {editing && <EquipmentForm device={editing === 'new' ? undefined : editing} onClose={() => { setEditing(null); setToast('设备台账已更新'); }} />}{toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>;
}
