import { zodResolver } from '@hookform/resolvers/zod';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Grid2X2, List, Pencil, Plus, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useForm } from 'react-hook-form';
import { useNavigate, useSearchParams } from 'react-router-dom';
import type { Equipment } from '@fengsui/shared';
import { equipmentInputSchema } from '@fengsui/shared';
import type { z } from 'zod';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, Empty, ErrorState, Loading, Modal, RiskBadge, StatusBadge, Toast } from '../components/ui';
import { api, patchJson, postJson } from '../services/api';

type FormData = z.infer<typeof equipmentInputSchema>;
const emptyForm: FormData = { deviceName: '', deviceType: '离心式引风机', systemArea: '烟气系统', manufacturer: '', model: '', installationDate: new Date().toISOString().slice(0, 10), runningStatus: '运行', operatingCondition: '稳定运行', responsiblePerson: '张工', responsibleUserId: 'demo-user', location: '' };

function EquipmentForm({ device, onClose }: { device?: Equipment; onClose: () => void }) {
  const queryClient = useQueryClient(); const [confirming, setConfirming] = useState(false);
  const { register, handleSubmit, formState: { errors }, getValues } = useForm<FormData>({ resolver: zodResolver(equipmentInputSchema), defaultValues: device ? { deviceName: device.deviceName, deviceType: device.deviceType, systemArea: device.systemArea, manufacturer: device.manufacturer, model: device.model, installationDate: device.installationDate, runningStatus: device.runningStatus, operatingCondition: device.operatingCondition, responsiblePerson: device.responsiblePerson, responsibleUserId: device.responsibleUserId, location: device.location } : emptyForm });
  const mutation = useMutation({ mutationFn: (body: FormData) => device ? patchJson<Equipment>(`/equipment/${device.deviceId}`, body) : postJson<Equipment>('/equipment', body), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ['equipment'] }); onClose(); } });
  const fields: Array<{ name: keyof FormData; label: string; type?: string }> = [{ name: 'deviceName', label: '设备名称' }, { name: 'deviceType', label: '设备类型' }, { name: 'systemArea', label: '系统区域' }, { name: 'manufacturer', label: '制造商' }, { name: 'model', label: '型号' }, { name: 'installationDate', label: '安装日期', type: 'date' }, { name: 'responsiblePerson', label: '负责人' }, { name: 'location', label: '安装位置' }];
  return <Modal title={device ? `编辑设备 · ${device.deviceName}` : '新增设备'} onClose={onClose}><form onSubmit={handleSubmit(() => setConfirming(true))}><div className="grid gap-4 sm:grid-cols-2">{fields.map((field) => <label key={field.name}><span className="label">{field.label}</span><input className="input" type={field.type} {...register(field.name)} />{errors[field.name] && <span className="mt-1 block text-xs text-red-500">{String(errors[field.name]?.message)}</span>}</label>)}<label><span className="label">运行状态</span><select className="input" {...register('runningStatus')}><option>运行</option><option>停机</option><option>检修</option><option>离线</option></select></label><label><span className="label">当前工况</span><select className="input" {...register('operatingCondition')}><option>停机</option><option>启动</option><option>低负荷</option><option>稳定运行</option><option>高负荷稳定运行</option></select></label></div><div className="mt-6 flex justify-end gap-2"><button type="button" className="btn-secondary" onClick={onClose}>取消</button><button className="btn-primary" disabled={mutation.isPending}>{device ? '保存修改' : '新增设备'}</button></div></form>{confirming && <div className="absolute inset-0 flex items-center justify-center rounded bg-white/95 p-6"><div className="max-w-sm text-center"><h3 className="font-semibold text-[#1F2329]">确认提交设备信息？</h3><p className="mt-2 text-sm text-[#646A73]">写操作将记录在设备台账中。当前为模拟演示数据。</p><div className="mt-5 flex justify-center gap-2"><button className="btn-secondary" onClick={() => setConfirming(false)}>返回检查</button><button className="btn-primary" onClick={() => mutation.mutate(getValues())}>确认提交</button></div></div></div>}</Modal>;
}

export function EquipmentPage() {
  const navigate = useNavigate(); const [params, setParams] = useSearchParams(); const [view, setView] = useState<'table' | 'card'>('table');
  const [editing, setEditing] = useState<Equipment | 'new' | null>(null); const [toast, setToast] = useState('');
  const query = useQuery({ queryKey: ['equipment'], queryFn: () => api<Equipment[]>('/equipment') });
  const rows = useMemo(() => {
    const all = query.data ?? []; const search = (params.get('search') ?? '').toLowerCase();
    return all.filter((item) => (!search || `${item.deviceName}${item.deviceId}${item.deviceType}`.toLowerCase().includes(search)) && (!params.get('deviceType') || item.deviceType === params.get('deviceType')) && (!params.get('systemArea') || item.systemArea === params.get('systemArea')) && (!params.get('riskLevel') || item.riskLevel === params.get('riskLevel')) && (!params.get('runningStatus') || item.runningStatus === params.get('runningStatus'))).sort((a, b) => params.get('sort') === 'healthDesc' ? b.healthScore - a.healthScore : a.healthScore - b.healthScore);
  }, [query.data, params]);
  const setFilter = (key: string, value: string) => { const next = new URLSearchParams(params); if (value) next.set(key, value); else next.delete(key); setParams(next); };
  if (query.isLoading) return <Loading />; if (query.isError) return <ErrorState error={query.error} retry={() => query.refetch()} />;
  const types = [...new Set((query.data ?? []).map((item) => item.deviceType))]; const areas = [...new Set((query.data ?? []).map((item) => item.systemArea))];
  return <div><PageHeader title="设备台账" description="统一管理关键设备档案、状态、工况和负责人" actions={<><button className="btn-primary" onClick={() => setEditing('new')}><Plus size={16} />新增设备</button></>} /><DemoDisclaimer compact />
    <div className="panel mt-4 p-4"><div className="flex flex-col gap-3 xl:flex-row xl:items-center"><div className="relative min-w-64 flex-1"><Search className="absolute left-3 top-2.5 text-[#8F959E]" size={17} /><input className="input pl-9" placeholder="搜索设备名称、编号或类型" value={params.get('search') ?? ''} onChange={(event) => setFilter('search', event.target.value)} /></div>{[['deviceType', '全部类型', types], ['systemArea', '全部区域', areas], ['riskLevel', '全部风险', ['健康', '关注', '二级预警', '高风险']], ['runningStatus', '全部状态', ['运行', '停机', '检修', '离线']]].map(([key, label, options]) => <select key={String(key)} className="input xl:w-40" value={params.get(String(key)) ?? ''} onChange={(event) => setFilter(String(key), event.target.value)}><option value="">{String(label)}</option>{(options as string[]).map((value) => <option key={value}>{value}</option>)}</select>)}<select className="input xl:w-40" value={params.get('sort') ?? 'healthAsc'} onChange={(event) => setFilter('sort', event.target.value)}><option value="healthAsc">健康度：低到高</option><option value="healthDesc">健康度：高到低</option></select><div className="flex rounded border border-[#D9DADC] p-0.5"><button className={`rounded-sm p-1.5 ${view === 'table' ? 'bg-[#F2F3F5] text-[#3A3F47]' : 'text-[#8F959E]'}`} onClick={() => setView('table')}><List size={17} /></button><button className={`rounded-sm p-1.5 ${view === 'card' ? 'bg-[#F2F3F5] text-[#3A3F47]' : 'text-[#8F959E]'}`} onClick={() => setView('card')}><Grid2X2 size={17} /></button></div></div><div className="mt-3 text-xs text-[#8F959E]">共 {rows.length} 台设备 · 支持按健康度排序</div></div>
    {view === 'table' ? <div className="panel mt-4 table-wrap">{rows.length ? <table className="data-table"><thead><tr><th>设备</th><th>类型 / 区域</th><th>状态 / 工况</th><th>健康度</th><th>关键指标</th><th>负责人</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{rows.map((item) => <tr key={item.deviceId} className="cursor-pointer" onClick={() => navigate(`/equipment/${item.deviceId}`)}><td><div className="font-semibold text-[#1F2329]">{item.deviceName}</div><div className="mt-1 font-mono text-xs text-[#8F959E]">{item.deviceId}</div></td><td><div>{item.deviceType}</div><div className="subtle mt-1">{item.systemArea}</div></td><td><StatusBadge status={item.runningStatus} /><div className="subtle mt-1">{item.operatingCondition}</div></td><td><div className="flex items-center gap-2"><span className="text-xl font-semibold">{item.healthScore}</span><RiskBadge level={item.riskLevel} /></div></td><td><div className="text-xs">振动 {item.vibration} mm/s</div><div className="mt-1 text-xs">温度 {item.temperature}℃</div></td><td>{item.responsiblePerson}</td><td className="text-xs">{new Date(item.updatedAt).toLocaleString('zh-CN')}</td><td><button className="rounded p-2 text-[#646A73] hover:bg-[#F2F3F5]" onClick={(event) => { event.stopPropagation(); setEditing(item); }}><Pencil size={15} /></button></td></tr>)}</tbody></table> : <Empty />}</div> : <div className="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{rows.map((item) => <button key={item.deviceId} className="panel p-5 text-left transition-colors hover:bg-[#FAFAFA]" onClick={() => navigate(`/equipment/${item.deviceId}`)}><div className="flex items-start justify-between"><div><div className="font-semibold text-[#1F2329]">{item.deviceName}</div><div className="mt-1 font-mono text-xs text-[#8F959E]">{item.deviceId}</div></div><RiskBadge level={item.riskLevel} /></div><div className="my-5 flex items-end gap-2"><span className="text-4xl font-semibold text-[#1F2329]">{item.healthScore}</span><span className="mb-1 text-xs text-[#8F959E]">健康度 / 100</span></div><div className="grid grid-cols-2 gap-2 rounded border border-[#E5E6EB] bg-[#FAFAFA] p-3 text-xs"><div><span className="text-[#8F959E]">振动</span><div className="mt-1 font-medium">{item.vibration} mm/s</div></div><div><span className="text-[#8F959E]">温度</span><div className="mt-1 font-medium">{item.temperature} ℃</div></div><div><span className="text-[#8F959E]">工况</span><div className="mt-1 truncate font-medium">{item.operatingCondition}</div></div><div><span className="text-[#8F959E]">负责人</span><div className="mt-1 font-medium">{item.responsiblePerson}</div></div></div></button>)}</div>}
    {editing && <EquipmentForm device={editing === 'new' ? undefined : editing} onClose={() => { setEditing(null); setToast('设备台账已更新'); }} />}{toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>;
}
