import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowLeft, Box, Check, ClipboardPlus, Clock3, History } from 'lucide-react';
import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { AiDiagnosis, Alert, Equipment, IndicatorKey, OperationLog, SparePartTransaction, TelemetryPoint, WorkOrder } from '@fengsui/shared';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, ErrorState, Loading, Modal, Panel, RiskBadge, StatusBadge, Toast } from '../components/ui';
import { api, idempotencyKey, postJson } from '../services/api';

interface HistoryData { alerts: Alert[]; workOrders: WorkOrder[]; logs: OperationLog[]; spareTransactions: SparePartTransaction[] }
const indicatorNames: Record<IndicatorKey, string> = { vibration: '振动', temperature: '温度', current: '电流', pressure: '压力', speed: '转速' };
const axisLabel = (value: string) => new Date(value).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' });

function MetricChart({ title, dataKey, unit, data, color }: { title: string; dataKey: keyof TelemetryPoint; unit: string; data: TelemetryPoint[]; color: string }) {
  return <Panel title={title}><div className="h-52 p-3"><ResponsiveContainer width="100%" height="100%"><LineChart data={data}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#EDEEF0" /><XAxis dataKey="timestamp" tickFormatter={axisLabel} minTickGap={30} tick={{ fontSize: 9, fill: '#8F959E' }} /><YAxis unit={unit} width={48} tick={{ fontSize: 9, fill: '#8F959E' }} domain={['auto', 'auto']} /><Tooltip labelFormatter={(value) => new Date(String(value)).toLocaleString('zh-CN')} formatter={(value) => [`${value} ${unit}`, title]} /><Line isAnimationActive={false} type="monotone" dataKey={dataKey} name={title} stroke={color} dot={false} strokeWidth={2} /></LineChart></ResponsiveContainer></div></Panel>;
}

function DiagnosisView({ diagnosis }: { diagnosis: AiDiagnosis }) {
  return <div className="space-y-4"><div className="rounded border border-orange-200 bg-orange-50 p-4"><div className="text-xs font-semibold text-orange-700">风险判断</div><p className="mt-1 text-sm font-medium text-orange-900">{diagnosis.riskJudgment}</p></div><div className="grid gap-4 sm:grid-cols-2"><section><h4 className="text-sm font-semibold">当前工况</h4><p className="mt-2 text-sm text-[#646A73]">{diagnosis.operatingCondition}</p></section><section><h4 className="text-sm font-semibold">异常指标</h4><p className="mt-2 text-sm text-[#646A73]">{diagnosis.abnormalIndicators.join('、')}</p></section><section className="sm:col-span-2"><h4 className="text-sm font-semibold">趋势证据</h4><ul className="mt-2 space-y-1 text-sm text-[#646A73]">{diagnosis.trendEvidence.map((item) => <li key={item}>· {item}</li>)}</ul></section><section><h4 className="text-sm font-semibold">疑似原因</h4><ul className="mt-2 space-y-1 text-sm text-[#646A73]">{diagnosis.suspectedCauses.map((item) => <li key={item}>· {item}</li>)}</ul></section><section><h4 className="text-sm font-semibold">推荐检查</h4><ul className="mt-2 space-y-1 text-sm text-[#646A73]">{diagnosis.inspectionItems.map((item) => <li key={item}>· {item}</li>)}</ul></section><section><h4 className="text-sm font-semibold">处理时限</h4><p className="mt-2 text-sm text-[#646A73]">{diagnosis.suggestedDeadline}</p></section><section><h4 className="text-sm font-semibold">关联备件</h4><p className="mt-2 text-sm text-[#646A73]">{diagnosis.relatedSpareParts.join('、') || '暂无明确关联备件'}</p></section></div><div className="rounded border border-[#E5E6EB] bg-[#FAFAFA] px-4 py-3 text-xs"><div className="flex items-center justify-between"><span>规则匹配度</span><strong className="text-[#3A3F47]">{Math.round(diagnosis.confidence * 100)}%</strong></div><p className="mt-1 text-[#8F959E]">基于模拟数据和规则库计算，仅供辅助参考。</p></div><p className="rounded border border-[#E5E6EB] p-3 text-xs leading-5 text-[#646A73]">{diagnosis.riskNotice}</p></div>;
}

export function EquipmentDetailPage() {
  const { deviceId = '' } = useParams(); const navigate = useNavigate(); const queryClient = useQueryClient();
  const [range, setRange] = useState('24h'); const [diagnosis, setDiagnosis] = useState<AiDiagnosis | null>(null); const [showHistory, setShowHistory] = useState(false); const [toast, setToast] = useState('');
  const deviceQuery = useQuery({ queryKey: ['equipment', deviceId], queryFn: () => api<Equipment>(`/equipment/${deviceId}`) });
  const telemetryQuery = useQuery({ queryKey: ['telemetry', deviceId, range], queryFn: () => api<TelemetryPoint[]>(`/equipment/${deviceId}/telemetry?range=${range}`) });
  const historyQuery = useQuery({ queryKey: ['history', deviceId], queryFn: () => api<HistoryData>(`/equipment/${deviceId}/history`) });
  const diagnose = useMutation({ mutationFn: () => postJson<AiDiagnosis>('/ai/diagnose', { deviceId, question: '请研判当前设备状态和主要风险' }), onSuccess: setDiagnosis });
  const acknowledge = useMutation({ mutationFn: (alertId: string) => postJson(`/alerts/${alertId}/acknowledge`, { operator: '黄浩' }), onSuccess: async () => { setToast('预警已确认'); await queryClient.invalidateQueries({ queryKey: ['history', deviceId] }); } });
  const createOrder = useMutation({ mutationFn: (alertId: string) => postJson<WorkOrder>(`/alerts/${alertId}/create-work-order`, { assignee: '张工', assigneeUserId: 'zhang-gong', idempotencyKey: idempotencyKey('create-order') }), onSuccess: (order) => { queryClient.invalidateQueries({ queryKey: ['history', deviceId] }); navigate(`/work-orders/${order.workOrderId}`); } });
  if (deviceQuery.isLoading || telemetryQuery.isLoading || historyQuery.isLoading) return <Loading />;
  if (deviceQuery.isError || !deviceQuery.data) return <ErrorState error={deviceQuery.error} retry={() => deviceQuery.refetch()} />;
  const device = deviceQuery.data; const telemetry = telemetryQuery.data ?? []; const history = historyQuery.data!;
  const openAlert = history.alerts.find((item) => !['已关闭', '误报'].includes(item.alertStatus));
  const activeAlert = openAlert ?? history.alerts[0];
  const relatedOrder = history.workOrders.find((item) => item.workOrderId === activeAlert?.relatedWorkOrderId);
  const closeReason = activeAlert?.alertStatus === '误报' ? '经人工复核后标记为误报' : relatedOrder?.status === '已完成' && relatedOrder.verificationResult ? '维修完成并验证通过' : '指标恢复或人工确认后关闭';
  const contributionData = activeAlert ? Object.entries(activeAlert.indicatorContributions).map(([key, value]) => ({ name: indicatorNames[key as IndicatorKey], 贡献度: value })) : [];
  return <div><PageHeader title={device.deviceName} description={`${device.deviceId} · ${device.deviceType} · ${device.location}`} actions={<><button className="btn-secondary" onClick={() => navigate('/equipment')}><ArrowLeft size={16} />返回设备台账</button>{device.deviceId === 'IDF-001' && <button className="btn-secondary" onClick={() => navigate('/digital-twin?equipment=IDF-01')}><Box size={16} />查看3D</button>}<button className="btn-primary" onClick={() => diagnose.mutate()} disabled={diagnose.isPending}>{diagnose.isPending ? '研判中…' : '立即研判'}</button></>} /><DemoDisclaimer compact />
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.5fr_1fr]">
      <Panel><div className="grid gap-6 p-6 sm:grid-cols-[170px_1fr]"><div className="flex flex-col items-center justify-center"><div className="relative h-36 w-36"><svg className="h-full w-full -rotate-90" viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="52" fill="none" stroke="#E5E6EB" strokeWidth="8" /><circle cx="60" cy="60" r="52" fill="none" stroke={device.healthScore >= 90 ? '#7FA58A' : device.healthScore >= 75 ? '#8293A8' : device.healthScore >= 60 ? '#C8894A' : '#B85C5C'} strokeWidth="8" strokeLinecap="butt" strokeDasharray={326.73} strokeDashoffset={326.73 * (1 - device.healthScore / 100)} /></svg><div className="absolute inset-0 flex flex-col items-center justify-center"><span className="text-4xl font-semibold text-[#1F2329]" data-testid="device-health-score">{device.healthScore}</span><span className="mt-1 text-xs text-[#8F959E]">当前健康度</span></div></div><div className="mt-3"><RiskBadge level={device.riskLevel} /></div></div><div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-[#1F2329]">设备实时状态</h2><p className="mt-1 text-xs text-[#8F959E]">更新于 {new Date(device.updatedAt).toLocaleString('zh-CN')}</p></div><StatusBadge status={device.runningStatus} /></div><div className="grid grid-cols-2 gap-x-6 gap-y-4 sm:grid-cols-3">{[['当前工况', device.operatingCondition], ['负责人', device.responsiblePerson], ['累计运行', `${device.runningHours.toLocaleString()} h`], ['制造商', device.manufacturer], ['型号', device.model], ['下次保养', device.nextMaintenanceDate]].map(([label, value]) => <div key={label}><div className="text-xs text-[#8F959E]">{label}</div><div className="mt-1 text-sm font-medium text-[#3A3F47]">{value}</div></div>)}</div></div></div></Panel>
      <Panel title={openAlert ? '当前辅助研判' : '最近已关闭预警'} extra={<span className="text-xs text-[#646A73]">规则匹配度 {activeAlert ? Math.round(activeAlert.confidence * 100) : 0}%</span>}><div className="p-5">{activeAlert ? <><p className="text-sm font-medium leading-6 text-[#3A3F47]">{activeAlert.aiAnalysis}</p>{!openAlert && <div className="mt-3 grid grid-cols-3 rounded border border-[#E5E6EB] bg-[#FAFAFA] text-sm"><div className="border-r border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">触发时健康度</div><div className="mt-1 font-semibold text-orange-700">{activeAlert.healthScore}</div></div><div className="border-r border-[#E5E6EB] p-3"><div className="text-xs text-[#8F959E]">当前健康度</div><div className="mt-1 font-semibold">{device.healthScore}</div></div><div className="p-3"><div className="text-xs text-[#8F959E]">关闭原因</div><div className="mt-1 text-xs text-[#3A3F47]">{closeReason}</div></div></div>}<div className="mt-4 rounded border border-[#E5E6EB] bg-[#FAFAFA] p-3"><div className="text-xs font-semibold text-[#646A73]">建议检查部位</div><div className="mt-2 flex flex-wrap gap-2">{activeAlert.maintenanceSuggestion.map((item) => <span key={item} className="rounded border border-[#D9DADC] bg-white px-2.5 py-1.5 text-xs text-[#646A73]">{item}</span>)}</div></div><div className="mt-4 flex items-center gap-2 text-sm text-orange-700"><Clock3 size={16} />建议处理时限：<strong>{activeAlert.suggestedDeadline}</strong></div><div className="mt-5 flex flex-wrap gap-2"><button className="btn-secondary" disabled={activeAlert.alertStatus !== '待确认'} onClick={() => acknowledge.mutate(activeAlert.alertId)}><Check size={15} />确认预警</button>{activeAlert.relatedWorkOrderId ? <button className="btn-primary" onClick={() => navigate(`/work-orders/${activeAlert.relatedWorkOrderId}`)}>查看关联工单</button> : openAlert ? <button className="btn-primary" onClick={() => createOrder.mutate(activeAlert.alertId)}><ClipboardPlus size={15} />生成维修工单</button> : null}</div></> : <p className="text-sm text-[#646A73]">当前无活动预警。</p>}</div></Panel>
    </div>
    <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-5">{[['振动', `${device.vibration} mm/s`], ['轴承温度', `${device.temperature} ℃`], ['电流', `${device.current} A`], ['压力', `${device.pressure} MPa`], ['转速', `${device.speed} r/min`]].map(([label, value], index) => <div key={label} className={`panel p-4 ${index < 2 && device.deviceId === 'IDF-001' && device.healthScore < 75 ? 'border-orange-200 bg-orange-50/30' : ''}`}><div className="text-xs text-slate-400">{label}</div><div className="mt-2 text-lg font-bold text-slate-800">{value}</div>{index < 2 && device.deviceId === 'IDF-001' && device.healthScore < 75 && <div className="mt-1 text-[11px] font-medium text-orange-600">持续上升</div>}</div>)}</div>
    <div className="mt-4 flex justify-end"><div className="flex rounded border border-[#D9DADC] bg-white p-0.5">{([['24h', '24小时'], ['7d', '7天'], ['30d', '30天']] as const).map(([value, label]) => <button key={value} onClick={() => setRange(value)} className={`rounded-sm px-3 py-1.5 text-xs ${range === value ? 'bg-[#4E5969] text-white' : 'text-[#646A73] hover:bg-[#F2F3F5]'}`}>{label}</button>)}</div></div>
    <div className="mt-3 grid gap-4 lg:grid-cols-2 xl:grid-cols-3"><MetricChart title="振动趋势" dataKey="vibration" unit="mm/s" data={telemetry} color="#C8894A" /><MetricChart title="轴承温度趋势" dataKey="temperature" unit="℃" data={telemetry} color="#B85C5C" /><MetricChart title="电流趋势" dataKey="current" unit="A" data={telemetry} color="#8293A8" /><MetricChart title="压力趋势" dataKey="pressure" unit="MPa" data={telemetry} color="#66788A" /><MetricChart title="转速趋势" dataKey="speed" unit="r/min" data={telemetry} color="#7FA58A" />
      <Panel title="指标异常贡献度"><div className="h-52 p-3"><ResponsiveContainer width="100%" height="100%"><BarChart data={contributionData} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#EDEEF0" /><XAxis type="number" unit="%" tick={{ fontSize: 9, fill: '#8F959E' }} /><YAxis type="category" dataKey="name" width={55} tick={{ fontSize: 10, fill: '#646A73' }} /><Tooltip formatter={(value) => [`${value}%`, '贡献度']} /><Bar isAnimationActive={false} dataKey="贡献度" fill="#C8894A" radius={[0, 2, 2, 0]} /></BarChart></ResponsiveContainer></div></Panel>
    </div>
    <div className="mt-4 grid gap-4 xl:grid-cols-[1.4fr_1fr]"><Panel title="健康度历史趋势"><div className="h-64 p-4"><ResponsiveContainer width="100%" height="100%"><AreaChart data={telemetry}><CartesianGrid strokeDasharray="3 3" stroke="#EDEEF0" /><XAxis dataKey="timestamp" tickFormatter={axisLabel} minTickGap={30} tick={{ fontSize: 9, fill: '#8F959E' }} /><YAxis domain={[40, 100]} unit="分" tick={{ fontSize: 9, fill: '#8F959E' }} /><Tooltip labelFormatter={(value) => new Date(String(value)).toLocaleString('zh-CN')} formatter={(value) => [`${value} 分`, '健康度']} /><Area isAnimationActive={false} type="monotone" dataKey="healthScore" stroke="#66788A" strokeWidth={2} fill="#91A7BF" fillOpacity={0.08} /></AreaChart></ResponsiveContainer></div></Panel><Panel title="历史与操作" extra={<button className="text-xs font-medium text-[#4E5969]" onClick={() => setShowHistory(true)}><History className="mr-1 inline" size={13} />查看完整历史</button>}><div className="space-y-4 p-5">{[...history.alerts.slice(0, 2).map((item) => ({ time: item.alertTime, title: `触发${item.riskLevel}`, detail: item.abnormalIndicators.join('、') })), ...history.workOrders.slice(0, 2).map((item) => ({ time: item.createdTime, title: `工单 ${item.status}`, detail: item.workOrderId }))].sort((a, b) => b.time.localeCompare(a.time)).map((item) => <div key={`${item.time}${item.title}`} className="relative border-l-2 border-[#D9DADC] pl-4"><span className="absolute -left-[5px] top-1 h-2 w-2 rounded-full bg-[#8F959E]" /><div className="text-sm font-medium text-[#3A3F47]">{item.title}</div><div className="mt-1 text-xs text-[#646A73]">{item.detail}</div><div className="mt-1 text-[11px] text-[#8F959E]">{new Date(item.time).toLocaleString('zh-CN')}</div></div>)}</div></Panel></div>
    {diagnosis && <Modal title={`辅助研判 · ${device.deviceName}`} onClose={() => setDiagnosis(null)}><DiagnosisView diagnosis={diagnosis} /></Modal>}
    {showHistory && <Modal title={`设备完整历史 · ${device.deviceName}`} onClose={() => setShowHistory(false)} width="max-w-4xl"><div className="grid gap-5 sm:grid-cols-3"><div><h3 className="font-semibold">历史预警（{history.alerts.length}）</h3>{history.alerts.map((item) => <div key={item.alertId} className="mt-3 rounded-lg border p-3 text-sm"><RiskBadge level={item.riskLevel} /><div className="mt-2">{item.abnormalIndicators.join('、')}</div><div className="subtle mt-1">{new Date(item.alertTime).toLocaleString('zh-CN')}</div></div>)}</div><div><h3 className="font-semibold">维修工单（{history.workOrders.length}）</h3>{history.workOrders.map((item) => <div key={item.workOrderId} className="mt-3 rounded-lg border p-3 text-sm"><StatusBadge status={item.status} /><div className="mt-2">{item.workOrderId}</div><div className="subtle mt-1">{item.repairResult ?? item.faultDescription}</div></div>)}</div><div><h3 className="font-semibold">使用备件 / 操作记录</h3>{history.spareTransactions.length === 0 && <div className="mt-3 text-sm text-slate-400">暂无已消耗备件</div>}{history.logs.map((item) => <div key={item.logId} className="mt-3 border-l-2 border-slate-200 pl-3 text-sm"><div className="font-medium">{item.action}</div><div className="subtle mt-1">{item.detail}</div></div>)}</div></div></Modal>}
    {toast && <Toast message={toast} onClose={() => setToast('')} />}{diagnose.isError && <Toast type="error" message={diagnose.error.message} onClose={() => diagnose.reset()} />}{createOrder.isError && <Toast type="error" message={createOrder.error.message} onClose={() => createOrder.reset()} />}
  </div>;
}
