import { useQuery } from '@tanstack/react-query';
import { Search, ShieldAlert } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { KnowledgeEntry } from '@fengsui/shared';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, Empty, ErrorState, Loading, Modal } from '../components/ui';
import { api } from '../services/api';

export function KnowledgePage() {
  const [search, setSearch] = useState(''); const [type, setType] = useState(''); const [selected, setSelected] = useState<KnowledgeEntry | null>(null);
  const query = useQuery({ queryKey: ['knowledge'], queryFn: () => api<KnowledgeEntry[]>('/knowledge') });
  const rows = useMemo(() => (query.data ?? []).filter((item) => (!type || item.deviceType === type) && (!search || JSON.stringify(item).toLowerCase().includes(search.toLowerCase()))), [query.data, search, type]);
  if (query.isLoading) return <Loading />; if (query.isError) return <ErrorState error={query.error} />;
  const types = [...new Set((query.data ?? []).map((item) => item.deviceType))];
  return <div><PageHeader title="运维知识库" description="沉淀设备故障现象、原因、检查步骤、处置方法与安全提醒" /><DemoDisclaimer compact /><div className="panel mt-4 p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className="input pl-9" placeholder="搜索故障现象、异常指标、原因或处理方法" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select className="input sm:w-48" value={type} onChange={(event) => setType(event.target.value)}><option value="">全部设备类型</option>{types.map((item) => <option key={item}>{item}</option>)}</select></div></div>
    {rows.length ? <div className="panel mt-4 divide-y divide-[#E5E6EB]">{rows.map((item) => <button key={item.knowledgeId} className="grid w-full gap-3 p-4 text-left transition-colors hover:bg-[#FAFAFA] md:grid-cols-[180px_1fr_220px] md:items-center" onClick={() => setSelected(item)}><div><span className="rounded border border-[#D9DADC] bg-[#F2F3F5] px-2 py-1 text-xs text-[#646A73]">{item.deviceType}</span><div className="mt-2 font-mono text-[11px] text-[#8F959E]">{item.knowledgeId}</div></div><div><h3 className="font-semibold text-[#1F2329]">{item.title}</h3><p className="mt-1 line-clamp-2 text-sm leading-6 text-[#646A73]">{item.faultPhenomenon}</p><div className="mt-2 flex flex-wrap gap-1.5">{item.abnormalIndicators.map((indicator) => <span key={indicator} className="rounded bg-orange-50 px-2 py-1 text-[11px] text-orange-700">{indicator}</span>)}</div></div><div className="text-xs leading-5 text-[#8F959E]">来源：{item.source}<br />更新于 {item.updatedAt}</div></button>)}</div> : <Empty />}
    {selected && <Modal title={selected.title} onClose={() => setSelected(null)} width="max-w-4xl"><div className="grid gap-5 sm:grid-cols-2"><section><h4 className="text-sm font-semibold text-[#1F2329]">故障现象</h4><p className="mt-2 text-sm leading-6 text-[#646A73]">{selected.faultPhenomenon}</p></section><section><h4 className="text-sm font-semibold text-[#1F2329]">适用工况</h4><p className="mt-2 text-sm leading-6 text-[#646A73]">{selected.applicableCondition}</p></section><section><h4 className="text-sm font-semibold text-[#1F2329]">可能原因</h4><ol className="mt-2 space-y-2 text-sm text-[#646A73]">{selected.possibleCauses.map((item, index) => <li key={item}>{index + 1}. {item}</li>)}</ol></section><section><h4 className="text-sm font-semibold text-[#1F2329]">检查步骤</h4><ol className="mt-2 space-y-2 text-sm text-[#646A73]">{selected.inspectionSteps.map((item, index) => <li key={item}>{index + 1}. {item}</li>)}</ol></section><section><h4 className="text-sm font-semibold text-[#1F2329]">处理方法</h4><ul className="mt-2 space-y-2 text-sm text-[#646A73]">{selected.handlingMethod.map((item) => <li key={item}>· {item}</li>)}</ul></section><section><h4 className="text-sm font-semibold text-[#1F2329]">关联备件</h4><div className="mt-2 flex flex-wrap gap-2">{selected.relatedSpareParts.map((item) => <span key={item} className="rounded border border-[#D9DADC] bg-[#F2F3F5] px-3 py-1.5 text-xs text-[#4E5969]">{item}</span>)}</div></section></div><div className="mt-5 flex items-start gap-2 rounded border border-red-200 bg-red-50 p-4 text-sm leading-6 text-red-800"><ShieldAlert className="mt-0.5 shrink-0" size={18} /><div><strong>安全提醒</strong><p>{selected.safetyReminder}</p></div></div><div className="mt-4 text-xs text-[#8F959E]">知识编号 {selected.knowledgeId} · 来源 {selected.source} · 更新时间 {selected.updatedAt}</div></Modal>}
  </div>;
}
