import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowDownToLine, ArrowUpFromLine, History, Search, TriangleAlert } from 'lucide-react';
import { useMemo, useState } from 'react';
import type { SparePart, SparePartTransaction } from '@fengsui/shared';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, Empty, ErrorState, Loading, Modal, StatusBadge, Toast } from '../components/ui';
import { api, idempotencyKey, postJson } from '../services/api';

function StockForm({ type, part, onClose, onSuccess }: { type: 'inbound' | 'outbound'; part: SparePart; onClose: () => void; onSuccess: () => void }) {
  const [quantity, setQuantity] = useState(1); const [remark, setRemark] = useState(type === 'inbound' ? '采购到货入库' : '手工领用出库');
  const mutation = useMutation({ mutationFn: () => postJson(`/spare-parts/${type}`, { partId: part.partId, quantity, operator: '黄浩', remark, idempotencyKey: idempotencyKey(`stock-${type}`) }), onSuccess });
  return <Modal title={`${type === 'inbound' ? '备件入库' : '备件出库'} · ${part.partName}`} onClose={onClose}><div className="mb-5 flex items-center justify-between rounded border border-[#E5E6EB] bg-[#FAFAFA] p-4"><span className="text-sm text-[#646A73]">当前库存</span><strong className="text-2xl">{part.currentStock} <small className="text-sm font-normal text-[#8F959E]">{part.unit}</small></strong></div><label><span className="label">{type === 'inbound' ? '入库' : '出库'}数量</span><input className="input" type="number" min="1" max={type === 'outbound' ? part.currentStock : undefined} value={quantity} onChange={(event) => setQuantity(Number(event.target.value))} /></label><label className="mt-4 block"><span className="label">备注</span><textarea className="input min-h-24 py-2" value={remark} onChange={(event) => setRemark(event.target.value)} /></label>{type === 'outbound' && quantity > part.currentStock && <div className="mt-3 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">库存不足，无法出库。</div>}{mutation.isError && <div className="mt-3 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{mutation.error.message}</div>}<div className="mt-6 flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>取消</button><button className="btn-primary" disabled={mutation.isPending || quantity <= 0 || (type === 'outbound' && quantity > part.currentStock)} onClick={() => mutation.mutate()}>确认{type === 'inbound' ? '入库' : '出库'}</button></div></Modal>;
}

export function SparePartsPage() {
  const queryClient = useQueryClient(); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [action, setAction] = useState<{ type: 'inbound' | 'outbound'; part: SparePart } | null>(null); const [historyPart, setHistoryPart] = useState<SparePart | null>(null); const [toast, setToast] = useState('');
  const query = useQuery({ queryKey: ['spare-parts'], queryFn: () => api<SparePart[]>('/spare-parts') });
  const transactions = useQuery({ queryKey: ['part-transactions', historyPart?.partId], queryFn: () => api<SparePartTransaction[]>(`/spare-parts/${historyPart!.partId}/transactions`), enabled: Boolean(historyPart) });
  const rows = useMemo(() => (query.data ?? []).filter((item) => (!status || item.stockStatus === status) && (!search || `${item.partName}${item.partId}${item.partCategory}`.toLowerCase().includes(search.toLowerCase()))), [query.data, search, status]);
  if (query.isLoading) return <Loading />; if (query.isError) return <ErrorState error={query.error} />;
  const stats = { total: query.data?.length ?? 0, enough: query.data?.filter((item) => item.stockStatus === '充足').length ?? 0, low: query.data?.filter((item) => item.stockStatus === '偏低').length ?? 0, empty: query.data?.filter((item) => item.stockStatus === '缺货').length ?? 0 };
  const success = async () => { setAction(null); setToast('库存已更新并写入操作记录'); await queryClient.invalidateQueries({ queryKey: ['spare-parts'] }); };
  return <div><PageHeader title="备件库存" description="备件余量、安全库存、出入库记录与维修工单联动管理" /><DemoDisclaimer compact />
    <div className="panel mt-4 grid grid-cols-2 overflow-hidden md:grid-cols-4">{[['备件种类', stats.total, 'text-[#1F2329]'], ['库存充足', stats.enough, 'text-[#1F2329]'], ['库存偏低', stats.low, 'text-orange-700'], ['缺货', stats.empty, 'text-red-700']].map(([label, value, color], index) => <button key={String(label)} className={`p-4 text-left transition-colors hover:bg-[#FAFAFA] ${index > 0 ? 'border-l border-[#E5E6EB]' : ''}`} onClick={() => setStatus(label === '库存充足' ? '充足' : label === '库存偏低' ? '偏低' : label === '缺货' ? '缺货' : '')}><div className={`text-xl font-semibold tabular-nums ${color}`}>{value}</div><div className="mt-1 text-xs text-[#646A73]">{label}</div></button>)}</div>
    {(stats.low > 0 || stats.empty > 0) && <div className="mt-4 flex items-center gap-2 rounded border border-orange-200 bg-orange-50 px-4 py-3 text-sm text-orange-800"><TriangleAlert size={17} /><span>当前有 {stats.low + stats.empty} 种备件达到或低于安全库存，工单完成前会再次校验实际库存。</span></div>}
    <div className="panel mt-4 p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className="input pl-9" placeholder="搜索备件名称、编号或分类" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select className="input sm:w-44" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部库存状态</option><option>充足</option><option>偏低</option><option>缺货</option></select></div></div>
    <div className="panel mt-4 table-wrap">{rows.length ? <table className="data-table"><thead><tr><th>备件</th><th>库存 / 安全库存</th><th>状态</th><th>适用设备</th><th>库位 / 供应商</th><th>操作</th></tr></thead><tbody>{rows.map((part) => <tr key={part.partId}><td><div className="font-medium text-[#1F2329]">{part.partName}</div><div className="mt-1 font-mono text-xs text-[#8F959E]">{part.partId} · {part.partCategory}</div></td><td><span className={`text-lg font-semibold ${part.stockStatus === '缺货' ? 'text-red-700' : part.stockStatus === '偏低' ? 'text-orange-700' : 'text-[#1F2329]'}`} data-testid={`stock-${part.partId}`}>{part.currentStock}</span><span className="ml-1 text-xs text-[#646A73]">{part.unit}</span><div className="mt-1 text-xs text-[#8F959E]">安全库存 {part.safeStock}{part.unit}</div></td><td><StatusBadge status={part.stockStatus} /></td><td><div className="max-w-xs text-xs leading-5">{part.applicableEquipment.join('、')}</div></td><td><div>{part.storageLocation}</div><div className="mt-1 text-xs text-[#8F959E]">{part.supplier}</div></td><td><div className="flex flex-wrap gap-1"><button className="btn-secondary min-h-8 px-2 py-1.5 text-xs" onClick={() => setAction({ type: 'inbound', part })}><ArrowDownToLine size={13} />入库</button><button className="btn-secondary min-h-8 px-2 py-1.5 text-xs text-orange-700 disabled:text-[#B7BBC1]" disabled={part.currentStock === 0} onClick={() => setAction({ type: 'outbound', part })}><ArrowUpFromLine size={13} />出库</button><button className="btn-secondary min-h-8 px-2 py-1.5 text-xs" onClick={() => setHistoryPart(part)}><History size={13} />记录</button></div></td></tr>)}</tbody></table> : <Empty />}</div>
    {action && <StockForm {...action} onClose={() => setAction(null)} onSuccess={success} />}{historyPart && <Modal title={`使用记录 · ${historyPart.partName}`} onClose={() => setHistoryPart(null)}>{transactions.isLoading ? <Loading /> : transactions.data?.length ? <div className="divide-y divide-[#E5E6EB] border border-[#E5E6EB]">{transactions.data.map((item) => <div key={item.transactionId} className="flex items-center justify-between p-4"><div><div className="flex items-center gap-2"><StatusBadge status={item.type} /><span className="text-sm font-medium">{item.remark}</span></div><div className="mt-2 text-xs text-[#8F959E]">{new Date(item.time).toLocaleString('zh-CN')} · {item.operator}{item.relatedWorkOrderId ? ` · ${item.relatedWorkOrderId}` : ''}</div></div><strong className={item.type === '入库' ? 'text-emerald-700' : 'text-orange-700'}>{item.type === '入库' ? '+' : '-'}{item.quantity}{historyPart.unit}</strong></div>)}</div> : <Empty title="暂无出入库记录" description="Mock 模式启动后产生的库存变更会记录在这里" />}</Modal>}{toast && <Toast message={toast} onClose={() => setToast('')} />}
  </div>;
}
