import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { ArrowRight, CheckCircle2, RotateCcw, Search } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import type { SparePart, WorkOrder, WorkOrderStatus } from '@fengsui/shared';
import { getNextWorkOrderActions } from '@fengsui/shared';
import { PageHeader } from '../components/PageHeader';
import { DemoDisclaimer, Empty, ErrorState, Loading, Modal, Panel, RiskBadge, StatusBadge, Toast } from '../components/ui';
import { api, idempotencyKey, postJson } from '../services/api';

const stages: WorkOrderStatus[] = ['待接单', '已接单', '检修中', '待验证', '已完成'];

function TransitionForm({ order, target, parts, onClose, onSuccess }: { order: WorkOrder; target: WorkOrderStatus; parts: SparePart[]; onClose: () => void; onSuccess: (order: WorkOrder) => void }) {
  const [note, setNote] = useState(''); const [inspection, setInspection] = useState(order.inspectionResult ?? '检查轴承润滑状态、轴承间隙、联轴器对中及地脚螺栓，发现润滑油劣化并伴有轴承轻微磨损。');
  const [repair, setRepair] = useState(order.repairResult ?? '更换风机轴承和润滑油，完成联轴器复核及地脚螺栓紧固。'); const [verification, setVerification] = useState('维修后振动降至3.1 mm/s、轴承温度降至68℃，连续稳定运行30分钟，指标恢复至工况基准范围。');
  const [health, setHealth] = useState(92); const [selected, setSelected] = useState<Record<string, number>>(() => Object.fromEntries((order.consumedSpareParts.length ? order.consumedSpareParts : order.deviceId === 'IDF-001' ? [{ partId: 'SP-001', quantity: 1 }, { partId: 'SP-002', quantity: 1 }] : []).map((item) => [item.partId, item.quantity])));
  const mutation = useMutation({ mutationFn: () => postJson<WorkOrder>(`/work-orders/${order.workOrderId}/transition`, { targetStatus: target, operator: '黄浩', note, inspectionResult: target === '待验证' ? inspection : undefined, repairResult: target === '待验证' ? repair : undefined, consumedSpareParts: target === '待验证' ? Object.entries(selected).filter(([, quantity]) => quantity > 0).map(([partId, quantity]) => ({ partId, quantity })) : undefined, healthScoreAfter: target === '已完成' ? health : undefined, verificationResult: target === '已完成' ? verification : undefined, idempotencyKey: idempotencyKey(`transition-${target}`) }), onSuccess });
  const label = target === '已接单' ? '确认接单' : target === '检修中' ? '开始检修' : target === '待验证' ? '提交维修结果' : target === '已完成' ? '完成验证并闭环' : target === '已取消' ? '取消工单' : `退回${target}`;
  return <Modal title={`${order.workOrderId} · ${label}`} onClose={onClose}><div className="mb-5 flex items-center gap-2 rounded border border-[#E5E6EB] bg-[#FAFAFA] p-3 text-sm"><StatusBadge status={order.status} /><ArrowRight size={15} className="text-[#8F959E]" /><StatusBadge status={target} /></div>
    {target === '待验证' && <div className="space-y-4"><label><span className="label">检查结果 <b className="text-red-500">*</b></span><textarea className="input min-h-24 py-2" value={inspection} onChange={(event) => setInspection(event.target.value)} /></label><label><span className="label">维修记录 <b className="text-red-500">*</b></span><textarea className="input min-h-24 py-2" value={repair} onChange={(event) => setRepair(event.target.value)} /></label><div><span className="label">实际消耗备件（完成工单时扣减）</span><div className="space-y-2 rounded-lg border border-slate-200 p-3">{parts.map((part) => <label key={part.partId} className="flex items-center justify-between gap-3"><span className="flex items-center gap-2 text-sm"><input type="checkbox" checked={selected[part.partId] !== undefined} onChange={(event) => setSelected((items) => { const next = { ...items }; if (event.target.checked) next[part.partId] = 1; else delete next[part.partId]; return next; })} />{part.partName}<span className="text-xs text-slate-400">库存 {part.currentStock}{part.unit}</span></span>{selected[part.partId] !== undefined && <input type="number" min="1" max={part.currentStock} className="input w-20" value={selected[part.partId]} onChange={(event) => setSelected({ ...selected, [part.partId]: Number(event.target.value) })} />}</label>)}</div></div></div>}
    {target === '已完成' && <div className="space-y-4"><label><span className="label">维修后健康度 <b className="text-red-500">*</b></span><input className="input" type="number" min="0" max="100" value={health} onChange={(event) => setHealth(Number(event.target.value))} /></label><label><span className="label">维修效果验证 <b className="text-red-500">*</b></span><textarea className="input min-h-28 py-2" value={verification} onChange={(event) => setVerification(event.target.value)} /></label><div className="rounded border border-emerald-200 bg-emerald-50 p-3 text-xs leading-5 text-emerald-800">完成后将自动更新设备健康度与风险等级、扣减实际消耗备件、关闭关联预警、写入维修历史及生成知识库候选案例。幂等键保证重复点击不会重复扣减库存。</div></div>}
    {!['待验证', '已完成'].includes(target) && <label><span className="label">处理说明{target === '已取消' ? ' *' : ''}</span><textarea className="input min-h-24 py-2" value={note} onChange={(event) => setNote(event.target.value)} placeholder="补充本次状态推进说明" /></label>}
    {mutation.isError && <div className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{mutation.error.message}</div>}<div className="mt-6 flex justify-end gap-2"><button className="btn-secondary" onClick={onClose}>取消</button><button data-testid={`confirm-transition-${target}`} className={target === '已取消' ? 'btn-danger' : 'btn-primary'} disabled={mutation.isPending || (target === '待验证' && (!inspection.trim() || !repair.trim())) || (target === '已完成' && !verification.trim())} onClick={() => mutation.mutate()}>{mutation.isPending ? '提交中…' : label}</button></div>
  </Modal>;
}

function WorkOrderDetail({ order, parts, onClose }: { order: WorkOrder; parts: SparePart[]; onClose: () => void }) {
  const queryClient = useQueryClient(); const navigate = useNavigate(); const [target, setTarget] = useState<WorkOrderStatus | null>(null); const [toast, setToast] = useState('');
  const onSuccess = async (updated: WorkOrder) => { setTarget(null); setToast(`工单已推进为“${updated.status}”`); await Promise.all([queryClient.invalidateQueries({ queryKey: ['work-orders'] }), queryClient.invalidateQueries({ queryKey: ['work-order', order.workOrderId] }), queryClient.invalidateQueries({ queryKey: ['equipment'] }), queryClient.invalidateQueries({ queryKey: ['spare-parts'] }), queryClient.invalidateQueries({ queryKey: ['alerts'] })]); };
  const actions = getNextWorkOrderActions(order.status);
  return <><Modal title="维修工单详情" onClose={onClose} width="max-w-5xl"><div className="flex flex-col justify-between gap-4 border-b border-[#E5E6EB] pb-4 sm:flex-row sm:items-center"><div><div className="flex items-center gap-3"><h3 className="font-mono text-lg font-semibold text-[#1F2329]">{order.workOrderId}</h3><StatusBadge status={order.status} /><RiskBadge level={order.riskLevel} /></div><button className="mt-2 text-sm font-semibold text-[#3A3F47] hover:underline" onClick={() => navigate(`/equipment/${order.deviceId}`)}>{order.deviceName}</button></div><div className="text-right"><div className="text-xs text-[#8F959E]">负责人</div><div className="mt-1 font-medium">{order.assignee}</div></div></div>
      <div className="mt-5 grid gap-4 lg:grid-cols-3"><Panel title="故障描述"><div className="p-4 text-sm leading-6 text-slate-600">{order.faultDescription}</div></Panel><Panel title="检修建议"><ul className="space-y-2 p-4 text-sm text-slate-600">{order.maintenanceSuggestion.map((item) => <li key={item}>· {item}</li>)}</ul></Panel><Panel title="工单信息"><div className="space-y-2 p-4 text-sm"><div className="flex justify-between"><span className="text-slate-400">创建人</span><span>{order.createdBy}</span></div><div className="flex justify-between"><span className="text-slate-400">创建时间</span><span>{new Date(order.createdTime).toLocaleString('zh-CN')}</span></div><div className="flex justify-between"><span className="text-slate-400">截止时间</span><span>{new Date(order.deadline).toLocaleString('zh-CN')}</span></div><div className="flex justify-between"><span className="text-slate-400">维修前健康度</span><strong>{order.healthScoreBefore}</strong></div>{order.healthScoreAfter !== undefined && <div className="flex justify-between"><span className="text-slate-400">维修后健康度</span><strong className="text-emerald-600">{order.healthScoreAfter}</strong></div>}</div></Panel></div>
      {(order.inspectionResult || order.repairResult || order.verificationResult) && <div className="mt-4 grid gap-4 lg:grid-cols-3">{order.inspectionResult && <Panel title="检查结果"><p className="p-4 text-sm leading-6 text-slate-600">{order.inspectionResult}</p></Panel>}{order.repairResult && <Panel title="维修结果"><p className="p-4 text-sm leading-6 text-slate-600">{order.repairResult}</p></Panel>}{order.verificationResult && <Panel title="验证结果"><p className="p-4 text-sm leading-6 text-slate-600">{order.verificationResult}</p></Panel>}</div>}
      <div className="mt-4 grid gap-4 lg:grid-cols-[1fr_1.3fr]"><Panel title="备件需求与消耗"><div className="p-4"><h4 className="text-xs font-semibold text-[#8F959E]">计划备件</h4>{order.requiredSpareParts.length ? order.requiredSpareParts.map((part) => <div key={part.partId} className="mt-2 flex justify-between text-sm"><span>{part.partName}</span><span>{part.quantity}{part.unit}</span></div>) : <p className="mt-2 text-sm text-[#8F959E]">无计划备件</p>}<h4 className="mt-5 text-xs font-semibold text-[#8F959E]">实际消耗</h4>{order.consumedSpareParts.length ? order.consumedSpareParts.map((part) => <div key={part.partId} className="mt-2 flex justify-between text-sm"><span>{part.partName}</span><strong>{part.quantity}{part.unit}</strong></div>) : <p className="mt-2 text-sm text-[#8F959E]">尚未登记</p>}</div></Panel><Panel title="处理时间线"><div className="space-y-4 p-5">{order.processingRecord.slice().reverse().map((record) => <div key={record.id} className="relative border-l-2 border-[#D9DADC] pl-4"><span className="absolute -left-[5px] top-1 h-2 w-2 rounded-full bg-[#8F959E]" /><div className="flex items-start justify-between gap-2"><div className="text-sm font-medium">{record.action}</div><span className="text-[11px] text-[#8F959E]">{new Date(record.time).toLocaleString('zh-CN')}</span></div><p className="mt-1 text-xs leading-5 text-[#646A73]">{record.detail}</p><p className="mt-1 text-[11px] text-[#8F959E]">操作人：{record.operator}</p></div>)}</div></Panel></div>
      <div className="mt-5 flex flex-wrap justify-end gap-2">{actions.map((action) => <button key={action} data-testid={`transition-${action}`} className={action === '已取消' ? 'btn-danger' : action === '检修中' && order.status === '待验证' ? 'btn-secondary' : 'btn-primary'} onClick={() => setTarget(action)}>{action === '已接单' ? '确认接单' : action === '检修中' && order.status === '已接单' ? '开始检修' : action === '检修中' ? <><RotateCcw size={15} />退回检修</> : action === '待验证' ? '提交维修结果' : action === '已完成' ? '完成验证并闭环' : '取消工单'}</button>)}</div>
      {order.status === '已完成' && <div className="mt-5 rounded border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="mr-2 inline" size={17} />工单已完成，关键结果已锁定；设备状态、库存、预警和维修历史已完成联动更新。</div>}
    </Modal>{target && <TransitionForm order={order} target={target} parts={parts} onClose={() => setTarget(null)} onSuccess={onSuccess} />}{toast && <Toast message={toast} onClose={() => setToast('')} />}</>;
}

export function WorkOrdersPage() {
  const { workOrderId } = useParams(); const navigate = useNavigate(); const [search, setSearch] = useState(''); const [status, setStatus] = useState('');
  const query = useQuery({ queryKey: ['work-orders'], queryFn: () => api<WorkOrder[]>('/work-orders') });
  const partsQuery = useQuery({ queryKey: ['spare-parts'], queryFn: () => api<SparePart[]>('/spare-parts') });
  const detailQuery = useQuery({ queryKey: ['work-order', workOrderId], queryFn: () => api<WorkOrder>(`/work-orders/${workOrderId}`), enabled: Boolean(workOrderId) });
  const rows = useMemo(() => (query.data ?? []).filter((item) => (!status || item.status === status) && (!search || `${item.workOrderId}${item.deviceName}${item.assignee}`.toLowerCase().includes(search.toLowerCase()))), [query.data, status, search]);
  if (query.isLoading || partsQuery.isLoading) return <Loading />; if (query.isError || partsQuery.isError) return <ErrorState error={query.error ?? partsQuery.error} />;
  return <div><PageHeader title="维修工单" description="按标准状态机推进维修任务，并联动设备、预警和备件库存" /><DemoDisclaimer compact />
    <div className="panel mt-4 grid grid-cols-2 overflow-hidden sm:grid-cols-5">{stages.map((item, index) => { const count = query.data?.filter((order) => order.status === item).length ?? 0; return <button key={item} className={`p-4 text-left transition-colors hover:bg-[#FAFAFA] ${index > 0 ? 'border-l border-[#E5E6EB]' : ''} ${status === item ? 'bg-[#F2F3F5]' : ''}`} onClick={() => setStatus(status === item ? '' : item)}><div className={`text-xl font-semibold tabular-nums ${item === '已完成' ? 'text-emerald-700' : 'text-[#1F2329]'}`}>{count}</div><div className="mt-1 text-xs text-[#646A73]">{item}</div></button>; })}</div>
    <div className="panel mt-4 p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 text-slate-400" size={17} /><input className="input pl-9" placeholder="搜索工单、设备或负责人" value={search} onChange={(event) => setSearch(event.target.value)} /></div><select className="input sm:w-44" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">全部状态</option>{[...stages, '已取消'].map((item) => <option key={item}>{item}</option>)}</select></div></div>
    <div className="panel mt-4 table-wrap">{rows.length ? <table className="data-table"><thead><tr><th>工单编号 / 创建时间</th><th>设备</th><th>风险等级</th><th>故障描述</th><th>负责人</th><th>截止时间</th><th>状态</th><th>操作</th></tr></thead><tbody>{rows.map((order) => <tr key={order.workOrderId} className="cursor-pointer" onClick={() => navigate(`/work-orders/${order.workOrderId}`)}><td><div className="font-mono text-xs font-semibold">{order.workOrderId}</div><div className="subtle mt-1">{new Date(order.createdTime).toLocaleString('zh-CN')}</div></td><td className="font-semibold text-slate-800">{order.deviceName}</td><td><RiskBadge level={order.riskLevel} /></td><td><div className="max-w-xs truncate">{order.faultDescription}</div></td><td>{order.assignee}</td><td className={new Date(order.deadline) < new Date() && !['已完成', '已取消'].includes(order.status) ? 'font-medium text-red-600' : ''}>{new Date(order.deadline).toLocaleString('zh-CN')}</td><td><StatusBadge status={order.status} /></td><td><button className="btn-secondary min-h-8 px-2.5 py-1.5">查看处理</button></td></tr>)}</tbody></table> : <Empty />}</div>
    {workOrderId && (detailQuery.isLoading ? <Modal title="维修工单详情" onClose={() => navigate('/work-orders')}><Loading /></Modal> : detailQuery.data ? <WorkOrderDetail order={detailQuery.data} parts={partsQuery.data ?? []} onClose={() => navigate('/work-orders')} /> : <Modal title="维修工单详情" onClose={() => navigate('/work-orders')}><ErrorState error={detailQuery.error} /></Modal>)}
  </div>;
}
